---
name: CI
'on':
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v4

      - name: Run ansible-lint.
        run: mise run lint

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2204
          # - debian12

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v4

      - name: Run Molecule tests.
        run: mise run molecule-test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
